<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Simple session 1</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
</head>

<body>
<form name="form1" method="post" action="session2.php">
<p>Please enter your name: <input name="name" type="text" id="name">
<input type="submit" name="Submit" value="Submit">
</p>
</form>
</body>
</html>
